name: Publish magicblock-delegation-program-api (dlp-api) Crate
on:
  release:
    types: [published]
  push:
    branches:
      - "release/v*"
  workflow_dispatch:
    inputs:
      dry_run:
        description: Run cargo publish in dry-run mode
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  rust_version: 1.84.1
  DRY_RUN: "false"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev

      - name: install rust
        shell: bash
        run: rustup toolchain install ${{ env.rust_version }} --profile minimal --component rustfmt --component clippy

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

  lint:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: check release manifest alignment
        run: bash ./.github/version_align.sh --check

      - name: install rust
        shell: bash
        run: rustup toolchain install ${{ env.rust_version }} --profile minimal --component rustfmt --component clippy

      - name: Run fmt
        run: cargo +${{ env.rust_version }} fmt -- --check

      - name: Run clippy
        run: cargo +${{ env.rust_version }} clippy -- --deny=warnings

  publish:
    needs: [install, lint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install rust
        shell: bash
        run: rustup toolchain install ${{ env.rust_version }} --profile minimal

      - name: run build
        run: cargo +${{ env.rust_version }} build

      - name: run tests (dlp-api cargo test)
        run: cargo +${{ env.rust_version }} test --manifest-path dlp-api/Cargo.toml

      - name: Set DRY_RUN based on trigger
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/v')
        run: echo "DRY_RUN=true" >> $GITHUB_ENV

      - name: Set DRY_RUN for manual runs
        if: github.event_name == 'workflow_dispatch'
        run: echo "DRY_RUN=${{ inputs.dry_run }}" >> $GITHUB_ENV

      - name: cargo publish
        run: |
          DRY_RUN_FLAG=""
          NO_VERIFY_FLAG=""
          if [ "${DRY_RUN}" = "true" ]; then
            DRY_RUN_FLAG="--dry-run"
            NO_VERIFY_FLAG="--no-verify"
          fi

          cargo +${{ env.rust_version }} publish $DRY_RUN_FLAG --manifest-path dlp-api/Cargo.toml --token "$CRATES_TOKEN" $NO_VERIFY_FLAG
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
          DRY_RUN: ${{ env.DRY_RUN }}
